### ISSUE TITLE
Error (E_UNKNOWN) :: Encountered an unexpected error

### ISSUE THREAD

**Issue by pdavid0** [Atlantis-Software/sails-hook-orm-offshore#3]
The real error is not reported in the stack trace, I had to debug in prod to understand what the *\* was going on.

```
Sending 400 ("Bad Request") response:
Error (E_UNKNOWN) :: Encountered an unexpected error at new WLError (/app/node_modules/sails-hook-orm-offshore/node_modules/offshore/lib/offshore/error/WLError.js:25:15)
at /app/node_modules/sails-hook-orm offshore/node_modules/offshore/lib/offshore/model/lib/defaultMethods/save.js:188:17
at /app/node_modules/sails-hook-orm-offshore/node_modules/async/lib/async.js:52:16
at /app/node_modules/sails-hook-orm-offshore/node_modules/async/lib/async.js:550:17
at /app/node_modules/sails-hook-orm-offshore/node_modules/async/lib/async.js:544:17
at _arrayEach (/app/node_modules/sails-hook-orm-offshore/node_modules/async/lib/async.js:85:13)
at Immediate.taskComplete (/app/node_modules/sails-hook-orm offshore/node_modules/async/lib/async.js:543:13)
at processImmediate [as _immediateCallback] (timers.js:383:17)
```

`//      console.log(JSON.stringify(err.failedTransactions));`
`[{"type":"insert","collection":"character_competences__competence_characters","criteria":{"competence_characters":1,"character_competences":301},"values":{"competence_characters":1,"character_competences":301},"err":{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid","invalidAttributes":{"id":[{"value":"117","rule":"unique","message":"A record with that`id`already exists (`117`)."}]}}}]
`

**Comment by atiertant** [comment]
@pdavid0 look like a validation error...

**Comment by pdavid0** [comment]
@atiertant Yes, absolutely, but logging the error
`sails.log.error(err);`

```
Sending 400 ("Bad Request") response:
Error (E_UNKNOWN) :: Encountered an unexpected error
```

Doesn't tell you what is going on. E_UNKNOWN is not helpful. 

E_VALIDATION would have been nice. 

If you want a PR tell me where to start 😄

**Comment by atiertant** [comment]
@pdavid0 i'm not sure that it's possible, how does sails handle error? 
look at `sails.log.error` code,
Is E_UNKNOWN is return when is return when error is not in a list of balderdashy project know error ?
is there a way to customize error in sails hook?

**Comment by airen29** [comment]
Same error here. E_UNKNOWN errors can be more "readable" through command
              `sails.log.error(err.failedTransactions);`
or simply
`console.log(err.failedTransactions);`

:+1:
